"""Change distance column type to String

Revision ID: d5956077c50e
Revises: f1a112c1f99b
Create Date: 2024-09-27 01:50:22.147304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5956077c50e'
down_revision = 'f1a112c1f99b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.alter_column('distance',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.alter_column('distance',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
